name: Workflow Github Develop Environment Execution

on: 
 push:
  branches: [ 'develop' ]

jobs:
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    env: 
      TAG: "@Success"
      TESTTYPE: "Secuencial"
      LANG: "@EN"
      ENV: DEV
    # Your other configuration variables here
    steps:
    - uses: actions/checkout@v3
    - name: valores de las variables de entorno
      run: echo "TAG= "$TAG,
                "TESTTYPE= "$TESTTYPE,
                "LANG= "$LANG
                "ENV= "$ENV
    - name: Ejecucion de pruebas
      continue-on-error: true
      run: |
          git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@/path/to/your/<AUTOMATION_PROJECT>.git"
          cd <AUTOMATION_PROJECT>
          mvn test -P$TESTTYPE -Dcrowdar.cucumber.filter="'$TAG'" -Dcrowdar.cucumber.filter.language="'$LANG'"
    - name: Subiendo informe
      uses: actions/upload-artifact@v3
      with:
        path: target/reports/